const today=new Date();const $=s=>document.querySelector(s);const params=new URLSearchParams(location.search);const readOnly=params.has('share');
function iso(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}function pretty(d,full=false){return d.toLocaleDateString(undefined,{month:full?'long':'short',day:'numeric',...(full?{year:'numeric'}:{})})}
function decodeShared(){try{return JSON.parse(decodeURIComponent(escape(atob(params.get('share')))))}catch{return null}}function encodeShared(value){return btoa(unescape(encodeURIComponent(JSON.stringify(value))))}
async function copyText(value){try{await navigator.clipboard.writeText(value);return true}catch{const area=document.createElement('textarea');area.value=value;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.focus();area.select();let copied=false;try{copied=document.execCommand('copy')}catch{}area.remove();return copied}}
const shared=readOnly?decodeShared():null;let viewDate=shared?.month?new Date(`${shared.month}-01T12:00:00`):new Date(today.getFullYear(),today.getMonth(),1);let selectedDate=new Date(viewDate.getFullYear(),viewDate.getMonth(),today.getDate());if(selectedDate.getMonth()!==viewDate.getMonth())selectedDate=new Date(viewDate.getFullYear(),viewDate.getMonth(),1);
const seed=[{id:1,date:iso(today),title:'Plan the week',time:'09:00',place:'At home',visibility:'show'},{id:2,date:iso(new Date(today.getFullYear(),today.getMonth(),Math.min(today.getDate()+2,28))),title:'Dentist appointment',time:'14:30',place:'Oak Street Clinic',visibility:'show'}];let events=shared?.events||JSON.parse(localStorage.getItem('daymark-events')||'null')||seed;const grid=$('#calendarGrid');
function visibleEvent(e){if(!readOnly)return e;if(e.visibility==='hide')return null;return e.visibility==='disguise'?{...e,title:'Personal',place:''}:e}
function render(){ $('#monthTitle').textContent=viewDate.toLocaleDateString(undefined,{month:'long',year:'numeric'});const first=new Date(viewDate.getFullYear(),viewDate.getMonth(),1),start=new Date(viewDate.getFullYear(),viewDate.getMonth(),1-first.getDay());grid.innerHTML='';for(let i=0;i<42;i++){const d=new Date(start);d.setDate(start.getDate()+i);const cell=document.createElement('div');cell.className='day'+(d.getMonth()!==viewDate.getMonth()?' other-month':'')+(iso(d)===iso(selectedDate)?' selected':'')+(iso(d)===iso(today)?' today':'');cell.innerHTML=`<div class="day-number">${d.getDate()}</div>`;events.filter(e=>e.date===iso(d)).map(visibleEvent).filter(Boolean).slice(0,2).forEach(e=>{const chip=document.createElement('div');chip.className='event-chip';chip.textContent=e.title;cell.append(chip)});cell.onclick=()=>{selectedDate=new Date(d);viewDate=new Date(d.getFullYear(),d.getMonth(),1);if(readOnly)render();else{render();openModal()}};grid.append(cell)}$('#selectedDateTitle').textContent=iso(selectedDate)===iso(today)?'Today':pretty(selectedDate,true);$('#selectedDayNumber').textContent=selectedDate.getDate();renderAgenda();renderUpcoming()}
function renderAgenda(){const list=$('#agendaList'),dayEvents=events.filter(e=>e.date===iso(selectedDate)).map(visibleEvent).filter(Boolean);list.innerHTML=dayEvents.length?dayEvents.map(e=>`<article class="agenda-item"><span class="agenda-dot"></span><div><h3>${e.title}</h3><div class="agenda-meta"><span>${e.time||'Anytime'}</span>${e.place?`<span>${e.place}</span>`:''}</div></div></article>`).join(''):'<p class="empty-state">Nothing planned for this day.</p>'}
function renderUpcoming(){const upcoming=events.filter(e=>e.date>=iso(today)).sort((a,b)=>(a.date+a.time).localeCompare(b.date+b.time)).map(visibleEvent).filter(Boolean).slice(0,3);$('#upcomingList').innerHTML=upcoming.map(e=>`<div class="upcoming-item"><span class="upcoming-date">${pretty(new Date(e.date+'T12:00:00'))}</span><span>${e.title}</span></div>`).join('')||'<p class="empty-state">No upcoming reminders.</p>'}
function openModal(){$('#eventDate').value=iso(selectedDate);$('#modal').classList.add('open');$('#modal').setAttribute('aria-hidden','false');setTimeout(()=>$('#eventTitle').focus(),50)}function closeModal(){$('#modal').classList.remove('open');$('#modal').setAttribute('aria-hidden','true');$('#eventForm').reset()}
if(readOnly){document.body.classList.add('read-only');$('.sidebar .eyebrow').textContent='Shared calendar';$('.sidebar h1').innerHTML='A little peek at<br><em>what matters.</em>';$('.sidebar .intro').textContent='This calendar was shared with you as a read-only view.';$('.sidebar .primary-button').remove();$('.share-button').remove();$('#openFromHeader').remove();$('#addAgendaEvent').remove();$('#prevMonth').disabled=false;$('.toolbar-hint').textContent='Read-only shared view'}else{['#addEventButton','#openFromHeader','#addAgendaEvent'].forEach(s=>$(s).onclick=openModal);$('#eventForm').onsubmit=e=>{e.preventDefault();events.push({id:Date.now(),date:$('#eventDate').value,title:$('#eventTitle').value.trim(),time:$('#eventTime').value,place:$('#eventPlace').value.trim(),visibility:$('#eventVisibility').value});localStorage.setItem('daymark-events',JSON.stringify(events));selectedDate=new Date($('#eventDate').value+'T12:00:00');viewDate=new Date(selectedDate.getFullYear(),selectedDate.getMonth(),1);closeModal();render()};$('#shareButton').onclick=async()=>{const url=new URL(location.href);url.search='';const safeEvents=events.filter(e=>e.visibility!=='hide').map(e=>e.visibility==='disguise'?{date:e.date,time:e.time,title:'Personal',place:'',visibility:'show'}:e);url.searchParams.set('share',encodeShared({month:iso(viewDate).slice(0,7),events:safeEvents}));const copied=await copyText(url.href);if(copied){$('#shareButton').textContent='✓ Copied';setTimeout(()=>$('#shareButton').textContent='↗ Share URL',1800)}else{prompt('Copy this share URL:',url.href)}}}
$('#closeModal').onclick=closeModal;$('#cancelModal').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal()};$('#prevMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()-1);render()};$('#nextMonth').onclick=()=>{viewDate.setMonth(viewDate.getMonth()+1);render()};$('#todayButton').onclick=()=>{selectedDate=new Date(today.getFullYear(),today.getMonth(),today.getDate());viewDate=new Date(today.getFullYear(),today.getMonth(),1);render()};render();
